<table width="202" border="0" cellpadding="0" cellspacing="0">
  <tr> 
    <td height="10" width="12">&nbsp; </td>
    <td height="10" width="210"> 
      <table width="120" border="1" bordercolor="#FFFFFF" cellspacing="0" cellpadding="0">
        <tr> 
          <td bordercolor="#999999" width="51"><font face="Verdana, Arial, Helvetica, sans-serif" size="1">&nbsp;<a href="ref:open($File)">Open</a></font></td>
          <td bordercolor="#999999" width="47"><font size="1" face="Verdana, Arial, Helvetica, sans-serif">&nbsp;<a href="ref:remove($File)">Remove</a></font></td>
        </tr>
      </table>
      <table width="166" bordercolor="#FFFFFF" cellpadding="0" cellspacing="0" border="1">
        <tr> 
          <td bordercolor="#999999" width="156"><font size="2" face="Verdana, Arial, Helvetica, sans-serif">&nbsp;%File</font></td>
        </tr>
      </table>
      <table width="20" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td height="4"></td>
        </tr>
      </table>
    </td>
  </tr>
</table>
